spring.application.name=LMS_backend
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/lms
spring.datasource.username=postgres
spring.datasource.password=nitinverma

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
